spring:
  application:
    name: student-api
    description: API to register Students
    version: 0.0.1
  profiles:
    active: default

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb
    username: mystudent
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
    password: 123
    user: root
    locations:
      - classpath:db/migration
    sql-migration-prefix: v

springdoc:
  packages-to-scan:
    - br.com.jcvpalma.studentapi.domain.controllers
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    operations-sorter: method

server:
  port: 8081
  servlet:
    context-path: /student-api

logging:
  level:
    root: INFO #TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    