version: '3.0'
services:
  mysql-student-local:
    image: mariadb:10.8.2
    container_name: mysql-student-local
    environment:
      - MARIADB_PASSWORD=123
      - MARIADB_USER=mystudent
      - MARIADB_ROOT_PASSWORD=123
      - MARIADB_DATABASE=studentdb
    ports:
      - 3306:3306
    networks:
      - mysql-network

  student-api-test:
    image: jcvpalma/student-api
    container_name: student-api-test
    environment:
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - 8081:8081
    networks:
      - spring-boot-network
    depends_on:
      - mysql-student-local

networks:
  mysql-network:
    driver: bridge
  spring-boot-network:
    driver: bridge